"""Run a model whose config says only what the data can support.

Upstream is read-only, so a zone that cannot be modelled this year cannot be removed in
code. It can be removed in **config**, which is an input like any other: `Config.all_zones`
is literally the keys of the `zones:` mapping (dispatch_model/config.py:47), and
`modelled_zones` is that list minus the border-only ones (rolling/assemble.py:275). Drop a
key and the zone leaves the LP. The backtest's border set is "the NTC table's keys
intersected with the active zones" (config.yaml:44), so its couplings go with it.

WHY THIS EXISTS. The 13-zone config declares four virtual clusters built from constituent
bidding zones. `IT_SOUTH` was added for issue #142, whose evidence is measured on 2024, and
one of its six constituents — `IT_CALA` — was carved out of `IT_SUD` afterwards. Ask
ENTSO-E for Calabria in 2019 and there is nothing to return, ever. The cluster is then built
from five sixths of itself and prices whatever that implies: measured, 181 EUR/MWh against a
market near 50, with 68 hours at the LP's value of lost load. It looks like a result.

Refusing the year was the first answer, and it is the wrong one: the other twelve zones are
perfectly modellable and France — the point of the exercise — does not need Italy's south.
So the cluster degrades away and the run says so.

PATHS ARE THE TRAP. Every relative path in this config resolves against the config FILE's
directory (`Config.resolve`, dispatch_model/config.py:74 for reports_dir). An overlay written
somewhere else silently moves `models_dir`, `reports_dir`, `output_dir`, the database and the
assumptions workbook with it. Rather than enumerate them — the list would rot — every string
value that names something existing beside the source config is rewritten absolute.
"""
from __future__ import annotations

from collections.abc import Iterable
from pathlib import Path
from typing import Any

import yaml


def _absolutise(node: Any, source_dir: Path) -> Any:
    """Rewrite every relative path in the tree to an absolute one.

    Existence-gated: a string is only treated as a path when something is actually there
    beside the source config, so ordinary strings ("multi_zone", "1h") pass through.
    """
    if isinstance(node, dict):
        return {k: _absolutise(v, source_dir) for k, v in node.items()}
    if isinstance(node, list):
        return [_absolutise(v, source_dir) for v in node]
    if isinstance(node, str) and node:
        candidate = Path(node)
        if not candidate.is_absolute():
            resolved = (source_dir / candidate)
            if resolved.exists():
                return str(resolved.resolve())
    return node


def write_zone_overlay(source_config: Path, target: Path, drop: Iterable[str]) -> list[str]:
    """Write `target`: `source_config` without `drop`. Returns the zones actually removed.

    Writing the overlay outside the code tree keeps the extracted release byte-identical to
    the archive it came from, which is the whole point of shipping code as a pinned archive.
    """
    source_config = Path(source_config)
    source_dir = source_config.parent
    raw = yaml.safe_load(source_config.read_text(encoding="utf-8")) or {}

    wanted = set(drop)
    zones = raw.get("zones") or {}
    removed = [z for z in zones if z in wanted]
    if not removed:
        return []

    raw = _absolutise(raw, source_dir)
    raw["zones"] = {z: meta for z, meta in (raw.get("zones") or {}).items()
                    if z not in wanted}
    # A border naming a zone that no longer exists is not merely redundant: `config.borders`
    # feeds the projection path directly, where there is no intersection to save it.
    raw["borders"] = [pair for pair in (raw.get("borders") or [])
                      if not (set(pair) & wanted)]

    target = Path(target)
    target.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# Generated by Dandelion. Do not edit.\n"
        "#\n"
        f"# {source_config} with these zones removed: {', '.join(removed)}.\n"
        "# They were dropped because the year being run has no data behind them — see\n"
        "# drivers/preflight.py check_cluster_zones. Relative paths have been rewritten\n"
        "# absolute so that models_dir, reports_dir, output_dir, the database and the\n"
        "# assumptions workbook still resolve to the same places the original config meant.\n"
    )
    target.write_text(header + yaml.safe_dump(raw, sort_keys=False, allow_unicode=True),
                      encoding="utf-8")
    return removed
